// @ts-nocheck
// Original campaign contracts ported from the supplied Python application.
// Runs only inside Supabase; private question keys never leave this engine.
import {catalog as templates} from './catalog.ts';
const clone=x=>structuredClone(x), norm=x=>String(x??'').trim().toLowerCase(), sites=['SAO','SVC','MAO','FRG'];
const now=()=>new Date().toISOString(), sum=a=>a.reduce((x,y)=>x+y,0), avg=a=>a.length?sum(a)/a.length:0;
const pick=(o,ks)=>Object.fromEntries(ks.map(k=>[k,o?.[k]??null]));
const bounded=x=>Math.max(0,Math.min(100,Math.round(x))), round=(x,n=4)=>Number(x.toFixed(n));
const eq=(a,b)=>String(a)===String(b), unique=a=>[...new Set(a)], id=()=>crypto.randomUUID();
export class ApiError extends Error {constructor(message,status=400){super(message);this.status=status;}}
function check(ok,message,status=400){if(!ok)throw new ApiError(message,status);}
export function evaluate(spec,a){
 const k=spec.key,m=spec.public.mode;const fraction=(got,exp)=>avg(Object.entries(exp||{}).map(([n,v])=>eq(got?.[n],v)?1:0));
 if(['choice','risk','scene','route'].includes(m))return eq(a,k.correct)?1:0;
 if(['inbox','quiz','story','camp'].includes(m))return fraction(a,k.answers);
 if(['communication','match'].includes(m))return fraction(a,k.assignments);
 if(['fill','process'].includes(m))return avg((k.answers||k.sequence).map((v,i)=>eq(a?.[i],v)?1:0));
 if(['detective','radar','pack'].includes(m)){const got=unique(Array.isArray(a)?a.map(String):[]),exp=k.selected.map(String);return Math.max(0,(got.filter(x=>exp.includes(x)).length-got.filter(x=>!exp.includes(x)).length)/Math.max(1,exp.length));}
 if(m==='simulator')return .8*fraction(a?.actions,k.answers)+.2*(eq(a?.priority,k.priority)?1:0);
 if(m==='aurora'){const useful=k.useful_evidence||[],got=unique(a?.investigated||[]);return .75*(eq(a?.decision,k.decision)?1:0)+.25*(useful.length?useful.filter(x=>got.includes(x)).length/useful.length:1);}
 return 0;
}
export function score(spec,perf,elapsed,seconds){
 if(perf<=0)return 0;const max=spec.max_score,speed=spec.speed_cap||0,base=max-speed,t=Math.max(10,seconds||spec.public.time||30)*1000;
 let value=elapsed<=t?base*perf+speed*perf*Math.max(0,1-elapsed/t):Math.max(100*perf,base*perf+(100-base)*perf*Math.min(1,(elapsed-t)/t));
 // Match Python's bankers rounding at exact halves.
 const f=Math.floor(value),d=value-f;return Math.max(0,Math.min(max,Math.abs(d-.5)<1e-9?f+(f%2):Math.round(value)));
}
const initialSim=track=>({integrity:75,risk:20,pressure:45,time:100,turn:0,route:track});
const initialAurora=()=>({actions_left:10,evidence:[],investigations_by_mission:{},risk:45,timeline_minutes:42,flags:[]});
const publicAurora=s=>s?{actions_left:s.actions_left,evidence_count:s.evidence.length,risk:s.risk,timeline_minutes:s.timeline_minutes,flags_count:s.flags.length}:null;
export class Engine {
 constructor(snapshot,content,actor){
  this.d=snapshot.state;this.content=content;this.actor=actor;this.users=snapshot.users;this.changes=[];this.events=[];this.backup=null;
  this.d.participants||={};this.d.votes||={};this.d.stories||=[];this.d.history||=[];
  this.d.config||={};const c=this.d.config;
  Object.assign(c,{event_name:'LG Compliance Challenge 2026',validation_enabled:true,version:8,tie_breaker:'score > performance > menor tempo'});
  c.stages||=clone(snapshot.stages);c.campaign||={mode:'month',phase:'onboarding',cumulative_stages:true,label:'Compliance Challenge 2026',show_campaign_banner:true,show_journey_soon:true};
  c.popular_vote||={open:true,label:'Votação Popular'};c.summit_challenge||={open:false,label:'Desafio Coletivo do Cume'};c.mission_times||={};
  c.extra_activities||=Object.fromEntries(Object.entries({onboarding_roulette:'Roleta de Boas-vindas',onboarding_detective:'Mini Detetive',detective:'Compliance Detective',camps:'Roleta dos Acampamentos'}).map(([k,label])=>[k,{open:true,label}]));
  for(const row of snapshot.legacy||[]){const key=norm(row.employee_id);if(this.d.participants[key])continue;const p=this.fresh(row);p.preferred_locale=row.locale;p.privacy_notice_acknowledgements=row.privacy_at?[{version:'2026.1',campaign_year:2026,acknowledged_at:row.privacy_at,locale:row.locale}]:[];
   for(const a of row.attempts||[]){p.attempts[a.stage]={attempt_id:a.id,track:a.track,status:a.completed_at?'completed':'in_progress',mission_order:a.mission_order,mission_results:a.results,answers:a.answers,opened_at:a.opened_at,started_at:a.started_at,completed_at:a.completed_at,simulator_state:a.stage===2?a.state:null,aurora_state:a.stage===3?a.state:null};p.stage_scores[a.stage]=sum(a.results.map(x=>x.score));p.completed[a.stage]=!!a.completed_at;}
   this.d.participants[key]=p;
  }
  this.key=norm(actor.employee_id);this.p=this.d.participants[this.key]||=this.fresh(actor);this.p.name=actor.name;this.p.site=actor.site;this.p.email=actor.email;
  this.profile=actor.role==='participant'?null:{username:actor.email.split('@')[0],role:actor.role,sites:actor.role==='super_admin'?sites:[actor.site],home_site:actor.site,label:actor.name,password_initialized:true,must_change:false};
 }
 fresh(u){return {employee_id:u.employee_id,email:u.email,site:u.site,name:u.name,masked_identity:'****'+String(u.employee_id).slice(-4),stage_scores:{1:0,2:0,3:0},completed:{1:false,2:false,3:false},badges:[],bonus_achievements:[],attempts:{},score_version:1,achievement_history:[],privacy_notice_acknowledgements:[],created_at:now(),updated_at:now()};}
 log(action,detail={}){this.events.push({action,detail});this.p.updated_at=now();}
 total(p){return sum(Object.values(p.stage_scores));}
 results(p){return Object.values(p.attempts||{}).flatMap(a=>a.mission_results||[]);}
 level(p){const x=this.total(p);return x>=35000?{name:'Líder de Integridade',start:35000,end:50235,next:'Cume',badge:'leader'}:x>=22000?{name:'Multiplicador',start:22000,end:35000,next:'Líder de Integridade',badge:'multiplier'}:x>=10000?{name:'Guardião',start:10000,end:22000,next:'Multiplicador',badge:'guardian'}:{name:'Explorador',start:0,end:10000,next:'Guardião',badge:'explorer'};}
 track(stage,p=this.p){return stage===1?'core':stage===3?'critical':['MAO','FRG'].includes(p.site)?'factory':'business';}
 missions(stage,track){return stage===2?this.content.game.stages[2][track]:this.content.game.stages[stage];}
 config(){return {...pick(this.d.config,['event_name','validation_enabled','campaign','stages','popular_vote','extra_activities','summit_challenge','tie_breaker']),stage_meta:this.content.game.stage_meta,localization:{default_locale:'pt-BR',supported_locales:['pt-BR','en-US','es-ES'],content_locale:'pt-BR'},privacy_notice:{version:'2026.1',campaign_year:2026,controller:'LG Electronics do Brasil Ltda.',contact:'dpobr@lge.com'}};}
 privacy(p){const a=p.privacy_notice_acknowledgements?.findLast(x=>x.version==='2026.1'&&x.campaign_year===2026);return {...this.config().privacy_notice,acknowledged:!!a,acknowledged_at:a?.acknowledged_at,locale:a?.locale};}
 addBadge(p,name,bonus=false,at=now(),source='journey'){
  const list=bonus?(p.bonus_achievements||=[]):(p.badges||=[]),fresh=!list.includes(name);if(fresh)list.push(name);
  p.achievement_history||=[];if(!p.achievement_history.some(x=>x.name===name&&x.campaign_year===2026&&x.score_version===p.score_version))p.achievement_history.push({name,campaign_year:2026,event:'Compliance Day 2026',score_version:p.score_version,earned_at:at,source,kind:bonus?'bonus':'journey'});
  return fresh;
 }
 reconcile(p){
  for(const [st,a] of Object.entries(p.attempts||{})){for(const r of a.mission_results||[]){if(r.performance<.999)continue;const spec=templates[['MAO','FRG'].includes(p.site)?'MAO':'SAO'].find(x=>x.stage===+st&&!x.bonus&&!x.automatic&&x.missions.length===1&&x.missions[0]===(r.content_mission||r.mission));if(spec)this.addBadge(p,spec.name,false,r.saved_at,`stage_${st}`);}
   if(a.status==='completed'){const names=+st===1?['Primeiro Acampamento']:+st===2?[a.track==='factory'?'Guardião da Operação':'Guardião das Relações','Acampamento 2']:['Cume Alcançado'];const perf=avg(a.mission_results.map(x=>x.performance));if(+st===3&&perf>=.85)names.push('Julgamento sob Pressão');if(perf>=.95)names.push('Precisão de Elite');for(const n of names)this.addBadge(p,n,false,a.completed_at,`stage_${st}_complete`);}
  }
  for(const [cid,c] of Object.entries(this.content.camps.camps)){const s=p.camp_progress?.[cid];if(s?.correct>=c.achievement.correct_required)this.addBadge(p,c.achievement.name,true,s.achievement_earned_at||p.updated_at,'camp_'+cid);}
  if(this.mastery(p).all_mastered)this.addBadge(p,'Mestre da Investigação',true,p.updated_at,'detective');
  if(p.onboarding_detective?.correct_conclusion&&p.onboarding_detective.coverage>=1)this.addBadge(p,'Olhar de Integridade',true,p.onboarding_detective.completed_at,'onboarding_detective');
  if(p.summit_common?.status==='completed')this.addBadge(p,'Cume em Equipe',true,p.summit_common.completed_at,'summit_common');
  const count=unique([...p.badges,...p.bonus_achievements]).filter(x=>x!=='Trilha das Conquistas').length;if(count>=5)this.addBadge(p,'Trilha das Conquistas',true);
 }
 catalog(p){this.reconcile(p);const specs=clone(templates[['MAO','FRG'].includes(p.site)?'MAO':'SAO']);const count=unique([...p.badges,...p.bonus_achievements]).filter(x=>x!=='Trilha das Conquistas').length,total=specs.filter(x=>!x.meta&&!x.level_meta).length,l=this.level(p);
  for(const s of specs){s.earned=s.level_meta||!!(s.bonus?p.bonus_achievements:p.badges).includes(s.name);s.practiceable=!s.bonus&&!s.automatic&&!!p.completed[s.stage];const h=p.achievement_history.findLast(x=>x.name===s.name&&x.score_version===p.score_version&&x.campaign_year===2026);if(h)s.earned_at=h.earned_at;
   if(s.meta){s.progress_count=count;s.total_available=total;s.tier=count>=total?'gold':count>=20?'silver':count>=10?'bronze':count>=5?'base':null;s.tier_label={gold:'Ouro',silver:'Prata',bronze:'Bronze',base:'Desbloqueada'}[s.tier]||'';s.asset='2026/'+({gold:'18-trilha-das-conquistas-ouro.png',silver:'17-trilha-das-conquistas-prata.png',bronze:'16-trilha-das-conquistas-bronze.png',base:'15-trilha-das-conquistas-normal.png'}[s.tier||'base']);s.asset_url='/assets/badges/'+s.asset;s.requirement=`Conquiste badges para evoluir sua Trilha das Conquistas. Progresso: ${count}/${count<5?5:count<10?10:count<20?20:total}.`;}
   if(s.level_meta){s.tier=l.badge;s.tier_label=l.name;s.asset='2026/'+({explorer:'13-primeiros-passos.png',guardian:'32-nivel-guardiao.png',multiplier:'33-nivel-multiplicador.png',leader:'34-nivel-lider-da-integridade.png'}[l.badge]);s.asset_url='/assets/badges/'+s.asset;s.requirement=`Seu nível evolui automaticamente pela pontuação da jornada. Nível atual: ${l.name}. Próximo nível: ${l.next}.`;}
  }return specs;
 }
 achievements(p,names){const c=this.catalog(p);return names.map(n=>{const s=c.find(x=>x.name===n);return {name:n,asset:s?.asset,earned_at:s?.earned_at||now(),event:'Compliance Day 2026',campaign_year:2026,timestamp_approximate:false};});}
 safeAttempts(p){return Object.fromEntries(Object.entries(p.attempts).map(([st,a])=>[st,{...pick(a,['attempt_id','status','track','started_at','completed_at','mission_order','mission_times','case_risk','outcome','simulator_state']),score:sum(a.mission_results.map(r=>r.score)),mission_results:a.mission_results.map(r=>pick(r,['mission','content_mission','score','performance','elapsed_ms','saved_at'])),aurora_state:publicAurora(a.aurora_state)}]));}
 participant(p){const catalog=this.catalog(p),r=this.results(p);return {...pick(p,['employee_id','masked_identity','site','name','stage_scores','completed','badges','bonus_achievements','score_version','updated_at']),total_score:this.total(p),level:this.level(p),badge_catalog:catalog,achievement_count:catalog.filter(x=>x.earned).length,campaign_year:2026,campaign:'Compliance Day 2026',previous_achievements:p.achievement_history.filter(x=>x.campaign_year!==2026),activities:this.activities(p),active_attempts:this.safeAttempts(p),missions_completed:r.length,performance:round(avg(r.map(x=>x.performance))),elapsed_ms:sum(r.map(x=>x.elapsed_ms)),preferred_locale:p.preferred_locale||null,resolved_locale:p.preferred_locale||'pt-BR',content_locale:'pt-BR',privacy_notice:this.privacy(p)};}
 rankingRows(site){return Object.entries(this.d.participants).filter(([k,p])=>!site||p.site===site).map(([key,p])=>({key,p,score:this.total(p),performance:avg(this.results(p).map(x=>x.performance)),elapsed_ms:sum(this.results(p).map(x=>x.elapsed_ms))})).sort((a,b)=>b.score-a.score||b.performance-a.performance||a.elapsed_ms-b.elapsed_ms||a.key.localeCompare(b.key));}
 ranking(site){const rows=this.rankingRows(site).map((x,i)=>({position:i+1,identity:x.p.masked_identity,score:x.score,performance:round(x.performance),elapsed_ms:x.elapsed_ms,site:x.p.site,is_current:x.key===this.key}));return {scope:site?'site':'global',site,top:rows.slice(0,10),current:rows.find(x=>x.is_current)||null};}
 champion(){const rows=this.rankingRows().filter(x=>this.eligible(x.p)),count=rows.length?Math.min(20,Math.max(1,Math.ceil(rows.length*.05))):0,final=Object.values(this.d.config.stages).every(s=>!s.open),champions=rows.slice(0,count).map((x,i)=>({position:i+1,identity:x.p.masked_identity,score:x.score,site:x.p.site,is_current:x.key===this.key}));return {final,count,eligible_completed:rows.length,champions,is_current:final&&champions.some(x=>x.is_current),current_position:champions.find(x=>x.is_current)?.position||null,winner:champions[0]||null};}
 me(){return {participant:this.participant(this.p),config:this.config(),rankings:{site:this.ranking(this.p.site),global:this.ranking()},champion:this.champion(),admin_profile:this.profile,privacy_required:!this.privacy(this.p).acknowledged};}
 extra(k){return this.d.config.extra_activities[k]?.open!==false;}
 mastery(p){const r=this.content.detective.cases.map(c=>p.detective_progress?.[c.id]);return {completed:r.filter(x=>x?.status==='completed').length,mastered:r.filter(x=>x?.status==='completed'&&x.performance>=.85).length,total:r.length,all_mastered:!!r.length&&r.every(x=>x?.status==='completed'&&x.performance>=.85)};}
 campSummary(p,cid){const spec=this.content.camps.camps[cid],s=p.camp_progress?.[cid]||{},achievement=spec.achievement,earned=p.bonus_achievements.includes(achievement.name),open=this.extra(+cid===0?'onboarding_roulette':'camps');return {camp:+cid,title:spec.title,open,unlocked:open&&(+cid===0||!!p.completed[cid]),spins:s.spins||0,answered:s.answered||0,correct:s.correct||0,best_streak:s.best_streak||0,active:!!s.active,achievement,achievement_earned:earned,correct_remaining:earned?0:Math.max(0,achievement.correct_required-(s.correct||0)),leaderboard:this.campLeaders(cid)};}
 campLeaders(cid,site){return Object.values(this.d.participants).filter(p=>!site||p.site===site).map(p=>({identity:p.masked_identity,...pick(p.camp_progress?.[cid],['correct','answered','best_streak'])})).filter(x=>x.answered>0).sort((a,b)=>b.correct-a.correct||b.best_streak-a.best_streak||a.answered-b.answered||a.identity.localeCompare(b.identity)).slice(0,3);}
 eligible(p){return [1,2,3].every(n=>p.completed[n]);}
 summitAttempt(a){return a?{...pick(a,['attempt_id','status','content_version','started_at','completed_at']),route:'common',answered:a.results.length,correct:a.results.filter(x=>x.correct).length,total_rounds:this.content.summit.rounds.length}:null;}
 activities(p){const m=this.mastery(p),i=p.onboarding_detective||{};return {onboarding:{roulette:this.campSummary(p,0),detective:{open:this.extra('onboarding_detective'),completed:i.status==='completed',correct:!!i.correct_conclusion,achievement_earned:p.bonus_achievements.includes('Olhar de Integridade')}},detective:{open:this.extra('detective'),unlocked:this.extra('detective')&&!!p.completed[1],...m},camps:[1,2].map(n=>this.campSummary(p,n)),summit_common:{open:this.d.config.summit_challenge.open,eligible:this.eligible(p),attempt:this.summitAttempt(p.summit_common)}};}
 times(){return [[1,'core'],[2,'business'],[2,'factory'],[3,'critical']].flatMap(([stage,track])=>this.missions(stage,track).map((s,i)=>({key:`${stage}:${track}:${i+1}`,stage,track,mission:i+1,type:s.public.type,mode:s.public.mode,default_time:s.public.time,time:this.d.config.mission_times[`${stage}:${track}:${i+1}`]||s.public.time})));}
 async handle(path,method='GET',body={}){
  const url=new URL(path,'https://campaign.invalid');path=url.pathname;const q=url.searchParams,p=this.p,c=this.d.config;
  if(path==='/api/me')return this.me();if(path==='/api/config')return this.config();if(path==='/api/health')return {ok:true,version:'6.1.0-restored',time:now()};
  if(path==='/api/privacy/acknowledge'){check(['pt-BR','en-US','es-ES'].includes(body.locale),'Idioma inválido.');if(!this.privacy(p).acknowledged)p.privacy_notice_acknowledgements.push({version:'2026.1',campaign_year:2026,acknowledged_at:now(),locale:body.locale});this.log('privacy_acknowledged');return {ok:true,privacy_notice:this.privacy(p)};}
  if(path==='/api/profile/locale'){check(['pt-BR','en-US','es-ES'].includes(body.locale),'Idioma inválido.');p.preferred_locale=body.locale;return {ok:true,participant:this.participant(p)};}
  if(path.startsWith('/api/admin/'))return this.admin(path,method,body,q);
  check(this.privacy(p).acknowledged,'Leia o aviso de privacidade antes de continuar.',403);
  let m;if((m=path.match(/^\/api\/stage\/([123])\/(.+)$/)))return this.stage(+m[1],m[2],body);
  if((m=path.match(/^\/api\/practice\/badge\/([^/]+)\/(start|mission|answer)$/)))return this.practice(decodeURIComponent(m[1]),m[2],body);
  if(path==='/api/voting')return this.voting(this.profile?.role==='super_admin'&&sites.includes(q.get('site'))?q.get('site'):p.site);
  if(path==='/api/voting/vote'){check(c.popular_vote.open,'A votação está encerrada.',403);const s=this.d.stories.find(s=>s.id===body.story_id&&s.site===p.site);check(s,'História não encontrada nesta unidade.');check(!this.d.votes[this.key],'Você já registrou seu voto.',409);this.d.votes[this.key]=s.id;this.log('popular_vote');return this.voting(p.site);}
  if(path==='/api/onboarding-detective'||path.startsWith('/api/onboarding-detective/'))return this.detective(true,null,path.split('/')[3]||'',body);
  if(path==='/api/detective'||(m=path.match(/^\/api\/detective\/([^/]+)(?:\/(start|restart|investigate|solve))?$/)))return this.detective(false,m?.[1],m?.[2]||'',body);
  if(path==='/api/camps')return {status:'active',ranked:false,camps:[0,1,2].map(n=>this.campSummary(p,n))};
  if((m=path.match(/^\/api\/camps\/([012])(?:\/(spin|answer))?$/)))return this.camp(+m[1],m[2]||'',body);
  if(path==='/api/summit-common'||(m=path.match(/^\/api\/summit-common\/(start|answer|round\/[0-9]+)$/)))return this.summit(m?.[1]||'',body);
  if(path==='/api/easter/fog/complete'){const unlocked=this.addBadge(p,'Mistério da Neblina',true)?['Mistério da Neblina']:[];return {ok:true,unlocked:!!unlocked.length,achievement:this.achievements(p,['Mistério da Neblina'])[0],achievements_unlocked:this.achievements(p,unlocked),participant:this.participant(p)};}
  if(path==='/api/progress/save')throw new ApiError('Pontuação livre desativada. Use o fluxo de missões validado pelo servidor.',410);
  throw new ApiError('Recurso não encontrado.',404);
 }
 stage(st,action,b){const p=this.p,track=this.track(st),missions=this.missions(st,track);let a=p.attempts[st];const max=sum(missions.map(x=>x.max_score));
  if(action==='status')return {stage:st,open:!!this.d.config.stages[st].open,completed:!!p.completed[st],track,max_score:max,mission_preview:missions.map((s,i)=>({mission:i+1,icon:s.public.icon,mode:s.public.mode,speed_test:['story','camp'].includes(s.public.mode)})),attempt:a?this.safeAttempts(p)[st]:null};
  check(this.d.config.stages[st].open,'Esta etapa está fechada.',403);check(st===1||p.completed[st-1],'Conclua a etapa anterior primeiro.',403);
  if(action==='start'){check(!p.completed[st],'Esta etapa já foi concluída.',409);if(!a){let order=Array.from({length:10},(_,i)=>i+1);if(st===1){order=[1,2,3,4,5,6,7,9];for(let i=order.length-1;i>0;i--){const j=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(i+1));[order[i],order[j]]=[order[j],order[i]];}order.push(8,10);}
    a=p.attempts[st]={attempt_id:id(),status:'in_progress',track,mission_order:order,mission_times:Object.fromEntries(this.times().filter(x=>x.stage===st&&x.track===track).map(x=>[x.mission,x.time])),mission_results:[],answers:{},started_at:now(),opened_at:null,simulator_state:st===2?initialSim(track):null,aurora_state:st===3?initialAurora():null,case_risk:st===3?45:0};this.log('stage_start',{stage:st});}
   return {attempt_id:a.attempt_id,track,next_mission:a.mission_results.length+1,stage_score:p.stage_scores[st],max_score:max,case_risk:a.case_risk,simulator_state:a.simulator_state,aurora_state:publicAurora(a.aurora_state)};
  }
  check(a,'Inicie a etapa antes de continuar.',409);check(a.track===track,'A unidade mudou. Procure o administrador.');
  if(action==='complete'){check(b.attempt_id===a.attempt_id,'Tentativa inválida.');check(a.mission_results.length===missions.length,'Conclua todas as missões antes de finalizar.');const before=[...p.badges];a.status='completed';a.completed_at||=now();p.completed[st]=true;this.reconcile(p);const unlocked=p.badges.filter(x=>!before.includes(x));return {score:p.stage_scores[st],max_score:max,average_performance:avg(a.mission_results.map(x=>x.performance)),badges_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),participant:this.participant(p),outcome:st===3?(a.case_risk<=30?'Risco controlado':'Pontos de atenção identificados'):null};}
  const number=action.startsWith('mission/')?+action.split('/')[1]:+b.mission;check(Number.isInteger(number)&&number>=1&&number<=missions.length,'Missão inválida.');const cid=a.mission_order[number-1],spec=missions[cid-1],done=a.mission_results.length;
  const response=(r,duplicate=false,unlocked=[])=>({accepted:true,duplicate,mission_result:r,stage_score:p.stage_scores[st],next_mission:a.mission_results.length+1,feedback:spec.feedback,badges_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),case_risk:a.case_risk,simulator_state:a.simulator_state,aurora_state:publicAurora(a.aurora_state)});
  if(action==='answer'&&number<=done){check(b.attempt_id===a.attempt_id,'Tentativa inválida.');return response(a.mission_results[number-1],true);}
  check(a.status==='in_progress'&&number===done+1,'Sequência de missões inválida.',409);
  if(action.startsWith('mission/')){a.opened_at||=now();const pub={...clone(spec.public),time:a.mission_times?.[cid]||spec.public.time,mission:number,content_mission:cid,stage:st,track,max_score:spec.max_score,speed_test:['story','camp'].includes(spec.public.mode),server_elapsed_ms:Math.max(0,Date.now()-Date.parse(a.opened_at))};if(st===2)pub.simulator_state=a.simulator_state;if(st===3){pub.aurora_state=publicAurora(a.aurora_state);pub.investigated=a.aurora_state.investigations_by_mission[cid]||[];pub.revealed_evidence=pub.investigated.map(eid=>({id:eid,...spec.evidence[eid]}));}return {mission:pub,stage_score:p.stage_scores[st],case_risk:a.case_risk,meta:this.content.game.stage_meta[st]};}
  check(b.attempt_id===a.attempt_id&&a.opened_at,'Tentativa inválida. Abra a missão antes de responder.');
  if(action==='investigate'){check(st===3,'Investigação indisponível.');const s=a.aurora_state,eid=b.evidence_id;check(Object.hasOwn(spec.evidence||{},eid),'Evidência não encontrada.');const used=s.investigations_by_mission[cid]||=[];if(!used.includes(eid)){check(used.length<(spec.public.action_limit||2)&&s.actions_left>0,'Limite de investigação atingido.',409);used.push(eid);s.actions_left--;s.evidence=unique([...s.evidence,eid]);}return {ok:true,evidence:{id:eid,...spec.evidence[eid]},aurora_state:publicAurora(s),investigated:used};}
  check(action==='answer','Operação inválida.');let answer=b.answer;if(st===3)answer={decision:b.answer?.decision,investigated:a.aurora_state.investigations_by_mission[cid]||[]};const elapsed=Math.max(0,Date.now()-Date.parse(a.opened_at)),perf=evaluate(spec,answer),r={mission:number,content_mission:cid,score:score(spec,perf,elapsed,a.mission_times?.[cid]),performance:round(perf),elapsed_ms:elapsed,saved_at:now()};
  if(st===2){const s=a.simulator_state,k=spec.key,impact=k.state_impact||{},apply=d=>{for(const [f,v] of Object.entries(d||{}))if(['integrity','risk','pressure','time'].includes(f))s[f]=bounded(s[f]+v);};for(const [eid,v]of Object.entries(k.answers))apply(impact[eq(answer?.actions?.[eid],v)?'correct':'wrong']);apply(impact[eq(answer?.priority,k.priority)?'priority_correct':'priority_wrong']);s.turn++;}
  if(st===3){const s=a.aurora_state,k=spec.key,correct=eq(answer.decision,k.decision);s.risk=bounded(s.risk+(correct?(k.risk_delta_correct??-4):(k.risk_delta_wrong??10)));s.risk=bounded(s.risk-Math.min(2,(k.useful_evidence||[]).filter(x=>answer.investigated.includes(x)).length));s.timeline_minutes=Math.max(0,s.timeline_minutes-4);if(!correct)s.flags=unique([...s.flags,...(k.flags_on_wrong||[])]);a.case_risk=s.risk;}
  const before=[...p.badges];a.mission_results.push(r);a.answers[number]=answer;a.opened_at=null;p.stage_scores[st]=sum(a.mission_results.map(x=>x.score));this.reconcile(p);this.log('mission_answer',{stage:st,mission:number,score:r.score});return response(r,false,p.badges.filter(x=>!before.includes(x)));
 }
 practice(name,action,b){const p=this.p,specb=this.catalog(p).find(x=>x.name===name);check(specb,'Conquista não encontrada.',404);p.badge_practice||={};let s=p.badge_practice[name];const payload=()=>({badge:name,stage:specb.stage,requirement:specb.requirement,missions:s.missions,current_index:s.results.length,total_missions:s.missions.length,next_mission:s.missions[s.results.length]||null,status:s.status,average_performance:s.average_performance});
  if(action==='start'){check(!specb.earned,'Esta conquista já foi desbloqueada.',409);check(specb.practiceable,'Conclua a etapa original antes de refazer este desafio.',409);s=p.badge_practice[name]={status:'in_progress',stage:specb.stage,missions:specb.missions,results:[],started_at:now()};return payload();}
  check(s?.status==='in_progress','Inicie o desafio da conquista.',409);const mission=s.missions[s.results.length],track=this.track(specb.stage),spec=this.missions(specb.stage,track)[mission-1];check(spec,'O desafio já foi concluído.',409);
  if(action==='mission'){s.opened_at||=now();const pub={...clone(spec.public),time:this.d.config.mission_times[`${specb.stage}:${track}:${mission}`]||spec.public.time,mission,content_mission:mission,stage:specb.stage,track,max_score:0,practice:true,speed_test:['story','camp'].includes(spec.public.mode)};if(spec.public.mode==='simulator')pub.simulator_state=initialSim(track);if(spec.public.mode==='aurora'){pub.aurora_state=publicAurora(initialAurora());pub.revealed_evidence=Object.entries(spec.evidence).map(([id,x])=>({id,...x}));pub.investigated=Object.keys(spec.evidence);}return {mission:pub,...payload()};}
  check(+b.mission===mission&&s.opened_at,'Abra e responda a próxima missão.',409);let a=b.answer;if(spec.public.mode==='aurora')a={decision:a?.decision??a,investigated:Object.keys(spec.evidence)};const perf=evaluate(spec,a),item={mission,performance:round(perf),elapsed_ms:Math.max(0,Date.now()-Date.parse(s.opened_at)),saved_at:now()};s.results.push(item);s.opened_at=null;const complete=s.results.length===s.missions.length;let success=false,unlocked=[];if(complete){s.average_performance=round(avg(s.results.map(x=>x.performance)));success=s.average_performance+1e-9>=specb.threshold;s.status=success?'completed_success':'completed_failed';s.completed_at=now();if(success&&this.addBadge(p,name,false,s.completed_at,'badge_practice'))unlocked=[name];}this.log('badge_practice_answer',{badge:name,mission,performance:perf});return {accepted:true,mission_result:{...item,score:0},feedback:spec.feedback,badges_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),complete,success,practice:payload()};
 }
 detective(intro,cid,action,b){const p=this.p,content=intro?this.content.onboarding.case:this.content.detective.cases.find(x=>x.id===cid),open=this.extra(intro?'onboarding_detective':'detective');
  if(!intro&&!cid)return {status:'active',ranked:false,open,unlocked:open&&!!p.completed[1],version:this.content.detective.version,cases:this.content.detective.cases.map(c=>({...pick(c,['id','title','subtitle','estimated','difficulty']),status:p.detective_progress?.[c.id]?.status||'not_started',performance:p.detective_progress?.[c.id]?.performance})),mastery:this.mastery(p)};
  check(content,'Caso não encontrado.',404);p.detective_progress||={};let state=intro?p.onboarding_detective:p.detective_progress[cid];const newState=()=>({status:intro?'not_started':'in_progress',started_at:intro?null:now(),actions_left:content.action_budget||3,opened_evidence:[]});
  if(intro&&!state)state=p.onboarding_detective=newState();
  const view=()=>{const opened=state?.opened_evidence||[];return {status:'active',ranked:false,open,unlocked:open&&(intro||!!p.completed[1]),case:pick(content,['id','title','subtitle','briefing','estimated','difficulty','conclusions','action_budget']),state:intro?state:{status:state?.status||'not_started',actions_left:state?.actions_left??content.action_budget,action_budget:content.action_budget,opened_count:opened.length,opened_evidence:opened,...(state?.status==='completed'?pick(state,['performance','correct_conclusion','completed_at']):{})},evidence:content.evidence.map(e=>({...pick(e,['id','type','label','preview']),opened:opened.includes(e.id),...(opened.includes(e.id)?{content:e.content}:{})})),...(intro?{achievement:{name:'Olhar de Integridade',earned:p.bonus_achievements.includes('Olhar de Integridade')}}:{})};};
  if(!action)return view();check(open,'Atividade fechada pelo Admin.',403);check(intro||p.completed[1],'Conclua a Etapa 1 para liberar o Compliance Detective.',403);
  if(action==='start'||action==='restart'){if(!state||action==='restart'){state=newState();if(intro)p.onboarding_detective=state;else p.detective_progress[cid]=state;}return view();}
  check(state,'Inicie este caso antes de investigar.',409);
  if(action==='investigate'){if(intro&&state.status==='completed')return view();check(state.status!=='completed','Reinicie o caso para investigar novamente.',409);const e=content.evidence.find(x=>x.id===b.evidence_id);check(e,'Evidência não encontrada.',404);const duplicate=state.opened_evidence.includes(e.id);if(!duplicate){check(state.actions_left>0,'Você não possui mais ações de investigação.',409);state.opened_evidence.push(e.id);state.actions_left--;}state.status='in_progress';state.started_at||=now();this.log('detective_investigate',{intro,case_id:cid,evidence_id:e.id});return intro?view():{duplicate,evidence:pick(e,['id','type','label','preview','content']),state:view().state};}
  check(action==='solve','Operação inválida.');check(state.status==='in_progress','Investigue evidências antes de registrar sua conclusão.',409);check(content.conclusions.some(x=>x.id===b.conclusion),'Conclusão inválida.');const opened=state.opened_evidence,required=content.key.required_evidence||[];check(opened.length,'Investigue pelo menos uma evidência antes de concluir.');const correct=b.conclusion===content.key.conclusion,hits=required.filter(x=>opened.includes(x)).length,coverage=required.length?hits/required.length:1,precision=hits/opened.length,performance=round(.6*(correct?1:0)+.3*coverage+.1*precision);Object.assign(state,{status:'completed',completed_at:now(),conclusion:b.conclusion,correct_conclusion:correct,coverage:round(coverage),performance,selected_evidence:clone(opened)});const name=intro?'Olhar de Integridade':'Mestre da Investigação',earned=intro?(correct&&coverage>=1):this.mastery(p).all_mastered,unlocked=earned&&this.addBadge(p,name,true,state.completed_at,intro?'onboarding_detective':'detective')?[name]:[];this.log('detective_solve',{intro,case_id:cid,performance});const response={ok:true,status:'completed',ranked:false,correct_conclusion:correct,coverage:round(coverage),precision:round(precision),performance,feedback:content.feedback,bonus_achievements_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),state};if(intro)response.achievement_feedback=earned?this.achievements(p,[name])[0]:null;else{response.mastery=this.mastery(p);response.key_evidence=content.evidence.filter(e=>required.includes(e.id)).map(e=>e.label);}return response;
 }
 camp(cid,action,b){const p=this.p,spec=this.content.camps.camps[cid];check(spec,'Acampamento não encontrado.',404);p.camp_progress||={};const s=p.camp_progress[cid]||={spins:0,answered:0,correct:0,streak:0,best_streak:0,seen:[],active:null},pub=x=>pick(x,['id','theme','prompt','options']);
  if(!action)return {status:'active',ranked:false,...this.campSummary(p,cid),rules:spec.rules||{},themes:unique(spec.challenges.map(x=>x.theme))};
  check(this.campSummary(p,cid).unlocked,'Esta roleta está bloqueada ou fechada pelo Admin.',403);
  if(action==='spin'){if(s.active){const ch=spec.challenges.find(x=>x.id===s.active.challenge_id);return {resumed:true,spin_id:s.active.spin_id,challenge:pub(ch),summary:this.campSummary(p,cid)};}const unseen=spec.challenges.filter(x=>!s.seen.includes(x.id)),pool=unseen.length?unseen:spec.challenges,ch=pool[Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*pool.length)];s.spins++;s.active={spin_id:id(),challenge_id:ch.id,started_at:now()};return {resumed:false,spin_id:s.active.spin_id,challenge:pub(ch),summary:this.campSummary(p,cid)};}
  check(s.active?.spin_id===b.spin_id,'Gire a roleta antes de responder.',409);const ch=spec.challenges.find(x=>x.id===s.active.challenge_id);check(ch.options.some(x=>eq(x.id,b.answer)),'Resposta inválida.');const correct=eq(ch.key,b.answer);s.answered++;if(correct){s.correct++;s.streak++;s.best_streak=Math.max(s.best_streak,s.streak);}else s.streak=0;s.seen=unique([...s.seen,ch.id]);s.active=null;let unlocked=[];if(s.correct>=spec.achievement.correct_required){s.achievement_earned_at||=now();if(this.addBadge(p,spec.achievement.name,true,s.achievement_earned_at,'camp_'+cid))unlocked=[spec.achievement.name];}this.log('camp_answer',{camp:cid,challenge_id:ch.id,correct});return {accepted:true,ranked:false,correct,feedback:ch.feedback,correct_answer:ch.key,bonus_achievements_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),summary:this.campSummary(p,cid),note:'A Roleta do Acampamento é treino e não altera o ranking oficial.'};
 }
 aggregate(){const rounds=this.content.summit.rounds,n=rounds.length,eligible=Object.values(this.d.participants).filter(p=>this.eligible(p)),buckets={};let started=0,completed=0,answers=0,correct=0;for(const p of eligible){const b=buckets[p.site]||={site:p.site,eligible:0,started:0,completed:0,answers:0,correct:0,elapsed_ms:0};b.eligible++;const a=p.summit_common;if(!a)continue;started++;b.started++;const cor=a.results.filter(r=>r.correct).length,ans=a.results.length;answers+=ans;correct+=cor;b.answers+=ans;b.correct+=cor;b.elapsed_ms+=sum(a.results.map(x=>x.elapsed_ms));if(a.status==='completed'){completed++;b.completed++;}}
  const target=Math.max(n,eligible.length*Math.max(1,Math.floor(n/2))),progress=Math.min(1,correct/Math.max(1,target)),risk=Math.max(0,Math.round(100*(1-progress))),rows=Object.values(buckets).map(b=>({...b,team_score:round(100*b.correct/Math.max(1,b.eligible*n),2),accuracy:round(b.answers?b.correct/b.answers:0),participation:round(b.answers/Math.max(1,b.eligible*n))})).sort((a,b)=>b.team_score-a.team_score||b.accuracy-a.accuracy||b.completed-a.completed||a.elapsed_ms-b.elapsed_ms||a.site.localeCompare(b.site));return {same_content_for_all:true,audience:'common',content_version:this.content.summit.version,round_ids:rounds.map(x=>x.id),eligible:eligible.length,started,completed,answers,correct,target_correct:target,cooperation:{progress:round(progress),risk_remaining:risk,status:risk<=0?'CONTROLADO':correct?'EM REDUÇÃO':'AGUARDANDO EXPEDIÇÃO'},competition:{basis:'mesmo conteúdo · desempenho da unidade = acertos / respostas disponíveis para participantes elegíveis',sites:rows}};
 }
 summit(action,b){const p=this.p,open=this.d.config.summit_challenge.open,eligible=this.eligible(p),rounds=this.content.summit.rounds;let a=p.summit_common;
  if(!action)return {status:'active',open,eligible,same_content_for_all:true,attempt:this.summitAttempt(a),achievement:p.bonus_achievements.includes('Cume em Equipe')?this.achievements(p,['Cume em Equipe'])[0]:null,aggregate:this.aggregate()};
  check(open&&eligible,'Conclua as três etapas e aguarde a abertura do Desafio Coletivo do Cume.',403);
  if(action==='start'){const resumed=!!a;if(!a)a=p.summit_common={attempt_id:id(),status:'in_progress',route:'common',content_version:this.content.summit.version,round_ids:rounds.map(x=>x.id),results:[],started_at:now()};return {resumed,same_content_for_all:true,attempt:this.summitAttempt(a),aggregate:this.aggregate()};}
  check(a,'Inicie o Desafio Coletivo do Cume.',409);const expected=a.results.length+1;
  if(action.startsWith('round/')){check(+action.split('/')[1]===expected&&expected<=rounds.length,'Sequência de rodadas inválida.',409);a.opened_at||=now();return {same_content_for_all:true,route:'common',round:{round:expected,...pick(rounds[expected-1],['id','theme','prompt','options']),audience:'common'},attempt:this.summitAttempt(a)};}
  check(b.attempt_id===a.attempt_id,'Tentativa coletiva inválida.',409);if(+b.round<expected&&+b.round>0)return {accepted:true,duplicate:true,result:a.results[+b.round-1],attempt:this.summitAttempt(a),aggregate:this.aggregate()};check(+b.round===expected&&expected<=rounds.length&&a.opened_at,'Abra e responda a próxima rodada.',409);const spec=rounds[expected-1];check(spec.options.some(x=>eq(x.id,b.answer)),'Resposta inválida.');const r={round:expected,round_id:spec.id,correct:eq(b.answer,spec.key),elapsed_ms:Math.max(0,Date.now()-Date.parse(a.opened_at)),saved_at:now()};a.results.push(r);a.opened_at=null;let unlocked=[];if(a.results.length===rounds.length){a.status='completed';a.completed_at=now();if(this.addBadge(p,'Cume em Equipe',true,a.completed_at,'summit_common'))unlocked=['Cume em Equipe'];}this.log('summit_answer',{round:expected,correct:r.correct});return {accepted:true,duplicate:false,result:r,feedback:spec.feedback,bonus_achievements_unlocked:unlocked,achievements_unlocked:this.achievements(p,unlocked),attempt:this.summitAttempt(a),aggregate:this.aggregate()};
 }
 voting(site,admin=false){const stories=this.d.stories.filter(s=>site==='ALL'||s.site===site),ids=stories.map(x=>x.id),my=ids.includes(this.d.votes[this.key])?this.d.votes[this.key]:null,votes=Object.values(this.d.votes).filter(v=>ids.includes(v)),open=this.d.config.popular_vote.open;const out={open,label:'Votação Popular',site_scope:site,stories,my_vote:my,total_votes:votes.length};if(admin||my||!open){out.results=stories.map(x=>({...x,votes:votes.filter(v=>v===x.id).length})).sort((a,b)=>b.votes-a.votes||a.id.localeCompare(b.id));out.winner=!open&&out.results[0]?.votes?out.results[0]:null;out.partial=open;}return out;}
 adminScope(p){return this.actor.role==='super_admin'||p.site===this.actor.site;}
 requireSuper(){check(this.actor.role==='super_admin','Função exclusiva do Super Admin.',403);}
 readiness(){return {ready:true,auth_ready:true,checks:{validation_enabled:true,authorized_users_loaded:this.users.length>0,session_secret_present:true,rbac_accounts_configured:true,admin_credentials_initialized:true},authorized_count:this.users.length,version:'6.1.0-restored',admin_key_source:'Supabase Auth',latest_backup:null,admin_accounts:this.users.filter(u=>u.role!=='participant').map(u=>({username:u.email.split('@')[0],role:u.role,sites:u.role==='super_admin'?sites:[u.site],home_site:u.site,label:u.name}))};}
 history(p,key,reason){this.d.history.push({participant:key,action:'score_version_closed',campaign_year:2026,event:'Compliance Day 2026',score_version:p.score_version,at:now(),actor:this.actor.email,reason,snapshot:clone(p)});p.score_version++;}
 reset(p,stage=1,extras=true){for(let n=stage;n<=3;n++){p.stage_scores[n]=0;p.completed[n]=false;delete p.attempts[n];}p.badges=[];p.badge_practice={};if(extras){p.detective_progress={};p.onboarding_detective=null;p.camp_progress={};p.summit_common=null;p.bonus_achievements=[];}this.reconcile(p);}
 admin(path,method,b,q){check(this.profile,'Acesso administrativo necessário.',403);const c=this.d.config;let m;
  if(path==='/api/admin/login')return {token:'current',profile:this.profile};
  if(path==='/api/admin/readiness')return this.readiness();
  if(path==='/api/admin/overview'){const scope=this.actor.role==='super_admin'?(sites.includes(q.get('site'))?q.get('site'):'ALL'):this.actor.site,rows=this.rankingRows(scope==='ALL'?null:scope).filter(x=>this.adminScope(x.p)).map(x=>{const p=x.p;this.reconcile(p);return {key:x.key,name:p.name,identity:p.employee_id,masked_identity:p.masked_identity,site:p.site,stage_scores:p.stage_scores,completed:p.completed,badges:p.badges,bonus_achievements:p.bonus_achievements,missions_completed:this.results(p).length,total_score:x.score,score_version:p.score_version,performance:round(x.performance),active:Object.entries(p.attempts).filter(([st,a])=>a.status==='in_progress').map(([st,a])=>({stage:+st,track:a.track,current_mission:a.mission_results.length+1,started_at:a.started_at})),updated_at:p.updated_at,password_set:!!this.users.find(u=>norm(u.employee_id)===x.key)?.auth_id};});const summit=this.aggregate();if(scope!=='ALL')summit.competition.sites=summit.competition.sites.filter(x=>x.site===scope);return {admin_profile:this.profile,admin_accounts:this.readiness().admin_accounts,site_scope:scope,available_sites:this.actor.role==='super_admin'?['ALL',...sites]:[this.actor.site],permissions:{super_admin:this.actor.role==='super_admin',can_global_control:this.actor.role==='super_admin',can_manage_participants:true,can_reset_passwords:true},config:this.config(),participants:rows,participant_count:rows.length,authorized_count:this.users.filter(u=>this.adminScope(u)&&(scope==='ALL'||u.site===scope)).length,champion:this.champion(),admin_champions:[],voting:scope==='ALL'?{open:c.popular_vote.open,site_scope:'ALL',by_site:Object.fromEntries(sites.map(s=>[s,this.voting(s,true)]))}:this.voting(scope,true),summit_common:summit,camp_leaderboards:Object.fromEntries([0,1,2].map(n=>[n,this.campLeaders(n,scope==='ALL'?null:scope)])),mission_times:this.times(),stage_max:{1:16235,2:16000,3:18000,total:50235},readiness:this.readiness()};}
  if(path==='/api/admin/export'||path==='/api/admin/export.csv'){const participants=Object.fromEntries(Object.entries(this.d.participants).filter(([k,p])=>this.adminScope(p)));if(path.endsWith('.csv')){const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['name','identity','site','score_version','stage1','stage2','stage3','total','performance','missions','badges'],...Object.values(participants).map(p=>[p.name,p.employee_id,p.site,p.score_version,p.stage_scores[1],p.stage_scores[2],p.stage_scores[3],this.total(p),avg(this.results(p).map(x=>x.performance)),this.results(p).length,[...p.badges,...p.bonus_achievements].join(' | ')])];return {csv:rows.map(r=>r.map(cell).join(',')).join('\r\n')};}return {exported_at:now(),admin_profile:this.profile,config:this.config(),authorized_users:{version:1,users:this.users.filter(u=>this.adminScope(u)).map(u=>pick(u,['employee_id','payroll_id','email','name','site','enabled']))},participants:{version:3,participants},score_history:this.d.history.filter(x=>participants[x.participant]),...(this.actor.role==='super_admin'?{champion:this.champion(),popular_stories:{stories:this.d.stories},popular_votes:{votes:this.d.votes}}:{})};}
  if((m=path.match(/^\/api\/admin\/participants\/([^/]+)(?:\/(reset(?:\/[123])?|reset-password|score-history))?$/))){const key=decodeURIComponent(m[1]),p=this.d.participants[key],action=m[2];check(p,'Participante não encontrado.',404);check(this.adminScope(p),'Participante fora do seu escopo.',403);if(action==='score-history')return {participant:{key,name:p.name,site:p.site},campaign_year:2026,campaign:'Compliance Day 2026',current_version:p.score_version,history:this.d.history.filter(x=>x.participant===key)};if(action==='reset-password'){const target=this.users.find(u=>norm(u.employee_id)===key);check(target,'Cadastro não encontrado.');check(target.role==='participant'||this.actor.role==='super_admin','Conta fora do seu escopo.',403);return {account_action:'recovery',target_email:target.email};}if(action?.startsWith('reset')){const stage=+action.split('/')[1]||1;this.history(p,key,'participant_reset');this.reset(p,stage,!action.includes('/'));this.log('participant_reset',{key,stage});return {ok:true,score_version:p.score_version};}check(method==='DELETE','Operação inválida.');this.history(p,key,'participant_deleted');delete this.d.participants[key];this.changes.push({kind:'disable',email:p.email});return {ok:true};}
  if(path==='/api/admin/authorized-users'&&method==='POST'){const site=String(b.site).toUpperCase();check(sites.includes(site),'Selecione uma unidade válida.');check(this.adminScope({site}),'Unidade fora do seu escopo.',403);check(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email||''),'Informe o e-mail para o cadastro seguro da conta.');check(String(b.name||'').trim().length>=2,'Informe o nome.');const employee_id=String(b.employee_id||b.matricula||'').trim();check(employee_id,'Informe a matrícula ou ID.');const aliases=[norm(employee_id),norm(b.email),norm(b.matricula)].filter(Boolean);check(!this.users.some(u=>[norm(u.employee_id),norm(u.email),norm(u.payroll_id)].some(x=>x&&aliases.includes(x))),'Cadastro duplicado.',409);const user={employee_id,email:norm(b.email),payroll_id:b.matricula||null,name:String(b.name).trim(),site,enabled:b.enabled!==false,role:'participant'};this.changes.push({kind:'add',user});return {ok:true,user,first_access:true,message:'Usuário adicionado. Gere um código de ativação para o primeiro acesso.'};}
  if(path==='/api/admin/voting/stories'){const grouped={},out=[],seen=new Set();check(Array.isArray(b.stories),'Histórias inválidas.');for(const raw of b.stories){const site=String(raw.site||b.site||this.actor.site).toUpperCase();check(sites.includes(site)&&this.adminScope({site}),'Unidade fora do seu escopo.',403);check((grouped[site]=(grouped[site]||0)+1)<=5,'No máximo 5 histórias por unidade.');const rawid=String(raw.id||'').trim(),sid=rawid.toUpperCase().startsWith(site+':')?rawid:site+':'+rawid;check(rawid&&!seen.has(sid)&&raw.title&&raw.story,'ID, título e texto são obrigatórios; IDs devem ser únicos.');seen.add(sid);let photo=String(raw.photo_url||'/assets/voting/story-placeholder.svg');check(photo.startsWith('/assets/')||photo.startsWith('https://'),'URL da imagem inválida.');out.push({id:sid,site,title:String(raw.title).slice(0,300),story:String(raw.story).slice(0,20000),preview:String(raw.preview||String(raw.story).replace(/\s+/g,' ').slice(0,177)).slice(0,400),author_label:String(raw.author_label||'').slice(0,200),photo_url:photo});}this.d.stories=this.d.stories.filter(x=>!grouped[x.site]).concat(out);this.d.votes=Object.fromEntries(Object.entries(this.d.votes).filter(([k,v])=>this.d.stories.some(x=>x.id===v)));this.log('stories_updated',{sites:Object.keys(grouped)});return {ok:true,count:out.length,sites:Object.keys(grouped)};}
  if(path==='/api/admin/mission-times'&&method==='GET')return {rows:this.times()};
  this.requireSuper();
  if((m=path.match(/^\/api\/admin\/accounts\/([^/]+)\/reset-password$/))){const u=this.users.find(u=>u.email.split('@')[0]===decodeURIComponent(m[1])&&u.role!=='participant');check(u,'Conta não encontrada.');check(u.email!==this.actor.email,'Altere sua senha pelo seu próprio acesso.');return {account_action:'recovery',target_email:u.email};}
  if(path==='/api/admin/campaign-display'){check(['show_campaign_banner','show_journey_soon'].includes(b.key),'Controle inválido.');c.campaign[b.key]=!!b.open;return this.config();}
  if(path==='/api/admin/campaign-phase'){const phases={onboarding:[],stage1:[1],stage2:[1,2],stage3:[1,2,3],closing:[1,2,3]};check(Object.hasOwn(phases,b.phase),'Fase inválida.');c.campaign.phase=b.phase;for(const n of [1,2,3])c.stages[n].open=phases[b.phase].includes(n);return this.config();}
  if((m=path.match(/^\/api\/admin\/stages\/([123])$/))){check(typeof b.open==='boolean','Estado inválido.');c.stages[m[1]].open=b.open;return this.config();}
  if(path==='/api/admin/close-all-stages'){for(const s of Object.values(c.stages))s.open=false;return {config:this.config(),champion:this.champion()};}
  if(path==='/api/admin/voting'){c.popular_vote.open=!!b.open;return this.voting(this.actor.site,true);}
  if(path==='/api/admin/summit-common'){c.summit_challenge.open=!!b.open;return {config:this.config(),aggregate:this.aggregate()};}
  if((m=path.match(/^\/api\/admin\/extra-activities\/([^/]+)$/))){check(Object.hasOwn(c.extra_activities,m[1]),'Atividade inválida.');c.extra_activities[m[1]].open=!!b.open;return this.config();}
  if(path==='/api/admin/reset-extra-scoreboards'){this.backup=clone(this.d);for(const p of Object.values(this.d.participants)){p.camp_progress={};p.detective_progress={};p.onboarding_detective=null;p.summit_common=null;p.bonus_achievements=p.bonus_achievements.filter(x=>x==='Mistério da Neblina');this.reconcile(p);}return {ok:true,participants_reset:Object.keys(this.d.participants).length};}
  if(path==='/api/admin/mission-times'){const valid=this.times();const overrides={};if(method!=='DELETE')for(const [key,value] of Object.entries(b.times||{})){const v=valid.find(x=>x.key===key);check(v&&Number.isInteger(value)&&value>=10&&value<=300,'Tempo inválido: use de 10 a 300 segundos.');if(value!==v.default_time)overrides[key]=value;}c.mission_times=overrides;return {ok:true,rows:this.times()};}
  if(path==='/api/admin/validation'){check(b.enabled!==false,'A validação de participantes é obrigatória no ambiente público.');return this.config();}
  if(path==='/api/admin/authorized-users/site'){const u=this.users.find(u=>[u.email,u.employee_id,u.payroll_id].some(x=>norm(x)===norm(b.identity)));check(u&&sites.includes(b.site),'Cadastro ou unidade inválida.');const p=this.d.participants[norm(u.employee_id)],old=u.site,changed=['MAO','FRG'].includes(old)!==['MAO','FRG'].includes(b.site);if(p){this.history(p,norm(u.employee_id),'site_change');p.site=b.site;if(changed)this.reset(p,2,false);}this.changes.push({kind:'site',email:u.email,site:b.site});return {ok:true,employee_id:u.employee_id,name:u.name,old_site:old,new_site:b.site,participant_updated:!!p,downstream_reset:changed};}
  if(path==='/api/admin/authorized-users'&&method==='PUT'){check(Array.isArray(b.users)&&b.users.length<=5000,'Lista inválida.');for(const u of b.users){check(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(u.email||'')&&sites.includes(u.site),'Cada cadastro precisa de e-mail e unidade válidos.');check(!u.role||u.role==='participant','Papéis administrativos são gerenciados separadamente.');}this.changes.push({kind:'import',users:b.users});return {ok:true,count:b.users.length};}
  if(path==='/api/admin/backup'){this.backup=clone(this.d);return {ok:true,backup:'campaign-'+now(),manifest:{created_at:now(),version:'6.1.0-restored'}};}
  if(path==='/api/admin/hard-reset-current-campaign'){check(b.confirmation==='RESET 2026','Digite exatamente: RESET 2026');this.backup=clone(this.d);const count=Object.keys(this.d.participants).length;for(const p of Object.values(this.d.participants)){this.reset(p);p.score_version=1;p.achievement_history=p.achievement_history.filter(x=>x.campaign_year!==2026);p.privacy_notice_acknowledgements=[];}this.d.history=[];this.d.votes={};return {ok:true,campaign_year:2026,participants_reset:count,recovery_backup:'before-reset-'+now()};}
  if(path==='/api/admin/security-report/export')return {version:'6.1.0-restored',generated_at:now(),controls:{private_question_keys:true,live_session_validation:true,server_clock:true,atomic_revision_writes:true,site_scope:true,mandatory_allowlist:true},pending:['Envio automático de recuperação por e-mail aguarda configuração de SMTP.']};
  throw new ApiError('Operação administrativa não encontrada.',404);
 }
}
